name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Mypy Check
        run: python -m mypy .
      - name: Unit tests
        run: python -m unittest

  repro:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repro-arg:
          [
            "bwv846_feature",
            "bach10_feature",
            "bwv846_align",
            "bach10_align",
            "bwv846_follow",
            "bach10_follow",
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Run repro
        run: python repro.py ${{ matrix.repro-arg }}
      - name: Upload Repro results
        uses: actions/upload-artifact@v2
        with:
          name: repro-results-${{ matrix.repro-arg }}
          path: repro_results/${{ matrix.repro-arg }}

  repro-bach10-plot-precision:
    runs-on: ubuntu-latest
    needs:
      - repro
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Download artifact (bach10_align)
        uses: actions/download-artifact@v2
        with:
          name: repro-results-bach10_align
          path: repro-results/bach10_align
      - name: Download artifact (bach10_follow)
        uses: actions/download-artifact@v2
        with:
          name: repro-results-bach10_follow
          path: repro-results/bach10_follow
      - name: List files
        run: ls -lR
      - name: Run plot_precision
        run: python repro.py bach10_plot_precision
      - name: Upload Repro results
        uses: actions/upload-artifact@v2
        with:
          name: repro-results-bach10_plot_precision
          path: repro_results/bach10_plot_precision

  repro-bwv846-plot-precision:
    runs-on: ubuntu-latest
    needs:
      - repro
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Download artifact (bwv846_align)
        uses: actions/download-artifact@v2
        with:
          name: repro-results-bwv846_align
          path: repro-results/bwv846_align
      - name: Download artifact (bwv846_follow)
        uses: actions/download-artifact@v2
        with:
          name: repro-results-bwv846_follow
          path: repro-results/bwv846_follow
      - name: List files
        run: ls -lR
      - name: Run plot_precision
        run: python repro.py bwv846_plot_precision
      - name: Upload Repro results
        uses: actions/upload-artifact@v2
        with:
          name: repro-results-bwv846_plot_precision
          path: repro_results/bwv846_plot_precision
