
name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Mypy Check
        run: python -m mypy .
      - name: Unit tests
        run: python -m unittest

  repro:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repro-arg:
          [
            "bwv846_feature",
            "bach10_feature",
            "bwv846_align",
            "bach10_align",
            "bwv846_follow",
            "bach10_follow",
          ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Cache requirements
        id: cache-requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Run install script
        run: scripts/install.sh
      - name: Run repro
        run: python repro.py ${{ matrix.repro-arg }}
      - name: Upload Repro results
        uses: actions/upload-artifact@v2
        with:
          name: repro-results-${{ matrix.repro-arg }}
          path: repro_results/${{ matrix.repro-arg }}
